# Generated by Django 4.2.7 on 2025-11-11 01:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_supportchat_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copytrader',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='trader_profiles'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana'), ('USDT', 'Tether (Trc)'), ('BNB', 'Binance Coin'), ('XRP', 'Ripple'), ('ADA', 'Cardano'), ('DOGE', 'Dogecoin')], max_length=10, unique=True),
        ),
    ]
