# Generated by Django 4.2.7 on 2025-11-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0005_systemlog_adminuser_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3),
        ),
    ]
