# Generated by Django 4.2.7 on 2026-02-26 19:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("platform_app", "0007_passwordresetcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("DIAMOND", "Diamond"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "minimum_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                    ),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank for unlimited",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total ROI % paid at end of duration",
                        max_digits=6,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="Plan duration in days"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text='List of feature strings, e.g. ["Daily reports", "Priority support"]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Highlight this plan on the plans page"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "investment_plans",
                "ordering": ["minimum_amount"],
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("BOT_PURCHASE", "Trading Bot Purchase"),
                    ("COPY_TRADE", "Copy Trading"),
                    ("TRADE", "Trade"),
                    ("SWAP", "Currency Swap"),
                    ("PROFIT", "Profit"),
                    ("COMMISSION", "Commission"),
                    ("BONUS", "Bonus"),
                    ("INVESTMENT", "Investment Plan"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_invested",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "expected_return",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("profit_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="platform_app.investmentplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_investments",
                "ordering": ["-start_date"],
            },
        ),
    ]
