# Generated by Django 4.2.7 on 2026-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "platform_app",
            "0008_investmentplan_alter_transaction_transaction_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletaddress",
            name="cryptocurrency",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin"),
                    ("ETH", "Ethereum"),
                    ("SOL", "Solana"),
                    ("USDT", "Tether (Trc)"),
                    ("BNB", "Binance Coin"),
                    ("XRP", "Ripple"),
                    ("ADA", "Cardano"),
                    ("DOGE", "Dogecoin"),
                    ("USDC (Sol)", "Dogecoin"),
                    ("USDC (Eth)", "Dogecoin"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
