# Generated by Django 4.2.7 on 2026-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_app", "0009_alter_walletaddress_cryptocurrency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletaddress",
            name="cryptocurrency",
            field=models.CharField(
                choices=[
                    ("BTC", "Bitcoin"),
                    ("ETH", "Ethereum"),
                    ("SOL", "Solana"),
                    ("USDT", "Tether (Trc)"),
                    ("BNB", "Binance Coin"),
                    ("XRP", "Ripple"),
                    ("ADA", "Cardano"),
                    ("DOGE", "Dogecoin"),
                    ("USDC (Sol)", "usdc (sol)"),
                    ("USDC (Eth)", "usdc (eth)"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
