# Generated by Django 5.2.4 on 2026-09-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_app", "0010_alter_walletaddress_cryptocurrency"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="useractivity",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
