# Generated by Django 5.2.4 on 2026-09-13 12:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_app", "0011_user_country_useractivity_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="CopyTraderPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("DIAMOND", "Diamond"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom name; defaults to the tier name",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum amount a user must invest to subscribe at this tier",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1"))
                        ],
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission charged for this tier (overrides the trader's default)",
                        max_digits=5,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text='List of feature strings, e.g. ["Priority support", "Weekly reports"]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="platform_app.copytrader",
                    ),
                ),
            ],
            options={
                "db_table": "copy_trader_plans",
                "ordering": ["price"],
                "unique_together": {("trader", "tier")},
            },
        ),
        migrations.AddField(
            model_name="copytradingsubscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="platform_app.copytraderplan",
            ),
        ),
    ]
